base_url = "https://savenko.tech"
title = "denver-code"
build_search_index = true
generate_feeds = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme = "toggle"

menu = [
    { name = "/projects", url = "/projects", weight = 1 },
    { name = "/posts", url = "/posts", weight = 2 },
    { name = "/about", url = "/about", weight = 4 },
]

socials = [
    { name = "telegram", url = "https://t.me/operatorSilence", icon = "telegram" },
    { name = "github", url = "https://github.com/denver-code/", icon = "github" },
]

[extra.analytics]
enabled = true

[extra.analytics.umami]
website_id = "fa6a920f-db21-406a-afe7-5caf4db6c791"
