base_url = "https://denver-code.github.io"
title = "denver-code"
build_search_index = true
generate_feed = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme = "toggle"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/talks", url = "/talks", weight = 3 },
    { name = "/about", url = "/about", weight = 4 },
]

socials = [
    { name = "telegram", url = "https://t.me/operatorSilence", icon = "telegram" },
    { name = "github", url = "https://github.com/denver-code/", icon = "github" },
]

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "not-matthias"

[extra.analytics.umami]
website_id = "cd7ad766-8974-4166-b17b-333e72a63202"
